### ISSUE TITLE
Information lost in fragments if app is idle for a long time.

### ISSUE THREAD

**Issue by emirua** [Party-Rock/android#11]
The detail and confirmation fragments lose the information from the Venue object when the application is not active for some time. When the application is resumed, the fragments don't set up the layout with the information from the venue that was received initially, and the layout only shows its preformat state. Solution is related with the fragment lifecycle or the eventbus implementation.

**Comment by emirua** [comment]
The issue is related to Android resource management. 
Dirty Quick Fix: The object had to be serialized to prevent deletion when activity was destroyed. This works partially as some data is still lost, like the features' icons. 
Real fix may be implementing a local database in android.

**Comment by gerardogtn** [comment]
Issue was fixed using a serializable implementation.
